CoreumFoundation/faucet

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/10)
=> enable running integration tests on faucet repo

main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/12)
=> add mnemonic key file path to the accepted flags

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/14)
=> Lint and test only `faucet` repo

pkg/http/http.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/16)
=> Fix linter issues after upgrading to golangci-lint v1.49.0

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/15)
=> Build docker images in CI so they might be used by `znet` later

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/18)
=> Enable CI znet test step

README.md
- Add documentation to README
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/13)
=> Added instructions to README

go.mod, go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/19)
=> Bump coreum version

go.mod, integration-tests/transfer_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/21)
=> fix test failure when queries go to different nodes

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/26)
=> Enable CI integration test step back

client/coreum/client.go, go.mod, go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/27)
=> use SimulateAndExecute flag to get gas info

pkg/http/http.go, pkg/http/middleware.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/32)
=> Fix parsing of X-Forwarded-For header

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/33)
=> Restore integration tests

.github/CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/34)
=> Add github/CODEOWNERS

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/35)
=> configured CI to run in parallel

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/faucet/41)
=> Dump docker logs on failure in CI

go.mod, go.sum, main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/42)
=> Update coreum dependency to support testnet & drop legacy key flag

app/app.go, app/errors.go, app/gen_mnemonic_and_fund.go, client/coreum/batcher.go, client/coreum/client.go, http/errors.go, http/http.go, main.go, pkg/config/config.go, pkg/http/http.go, pkg/http/middleware.go, pkg/limiter/limiter.go, pkg/limiter/types.go, pkg/logger/logger.go, pkg/signal/signal.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/43)
=> Apply linter config changes

go.mod, go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/44)
=> Upgrade coreum version

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/50)
=> Adjust CI to be similar to those in other repos

client/coreum/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/57)
=> Use multisend to transfer funds

.github/workflows/ci.yml, README.md, integration-tests/transfer_test.go, main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/59)
=> Increase default amount sent in faucet, set default value to 100 CORE.

http/limiter.go, pkg/limiter/limiter.go, pkg/limiter/types.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/64)
=> Fix rate limiter to consume limit only if request was a success

.github/workflows/ci.yml, integration-tests/transfer_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/66)
=> Remove unused zap logger from the integration tests.

.github/workflows/ci.yml, go.mod, go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/68)
=> Update coreum-tools and remove  --log-format=yaml from CI.

.github/workflows/ci.yml, integration-tests/transfer_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/69)
=> Remove restore key for the docker cache to reset it on reinit.

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/70)
=> Add binaries cache for the CI.

client/coreum/batcher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/71)
=> removed a TODO line

.github/workflows/release.yml, main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/74)
=> Store checksums of released `faucet` binaries

build/cmd/main.go, build/faucet/build.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/77)
=> Remove `ensureRepo` function

.github/workflows/ci.yml, build/cmd/main.go, build/faucet/build.go, build/go.mod, build/go.sum, build/index.go, go.work.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/80)
=> Upgrade builder and CI

build/go.mod, build/go.sum, go.mod, go.sum
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/84)
=> Update `crust` and `coreum` builders

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile, build/faucet/build.go, build/index.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/85)
=> Use self-hosted runner

build/faucet/build.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/faucet/87)
=> Remove `znet` environment on integration test failure
